{{- if .Values.budget.minAvailable -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "flask-socket-io.fullname" . }}
  labels:
{{ include "flask-socket-io.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "flask-socket-io.fullname" . }}
  minAvailable: {{ .Values.budget.minAvailable }}
  {{- end -}}
