apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-socket-io.fullname" . }}-secrets
  labels:
{{ include "flask-socket-io.labels" . | indent 4 }}
type: Opaque
data:
  REDIS_HOST: {{ .Values.REDIS_HOST | b64enc | quote }}
  SECRET_KEY: {{ .Values.SECRET_KEY | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.REDIS_PASSWORD | b64enc | quote }}
